### ISSUE TITLE
Can we change the peer dependency version please?

### ISSUE THREAD

**Issue by simlu** [jaydp17/serverless-plugin-ncc#2]
In particular:
https://github.com/jaydp17/serverless-plugin-ncc/blob/master/package.json#L41

Ideally this should be `>=`. Since we are getting warnings in yarn now, this is actually critical. will open pr shortly.

Reference:
https://docs.npmjs.com/files/package.json#dependencies

**Comment by simlu** [comment]
https://github.com/jaydp17/serverless-plugin-ncc/pull/3/files

**Comment by jaydp17** [comment]
makes sense, and thanks for the PR @simlu.

I've merged the changes and it's available in `v0.2.1`

**Comment by simlu** [comment]
Sweet! Thank you for the quick reply!
